### PR TITLE
Feature xplat targets

### LINKED ISSUE #134: Add support for cross-platform targets
Currently a target can only be associated with one platform, however a common use case is to have multiple targets per-platform from a single source set to enable that target to be consumed on multiple platforms.

This feature would enable a target to specify multiple platforms, as follows:

**YAML/JSON**
```yaml
targets:
  My framework:
    platform:
    - ios
    - tv
```

**Specfile**
```ruby
target 'My framework' do
  platform 'ios'
  platform 'tv'
end
```

This would perform a few actions within struct:

- For each platform, a target suffixed by the platform name would be generated:
  - My framework-iOS
  - My framework-tvOS
- Each target would define the preprocessor variable PLATFORM_{PLATFORM_NAME}
- Each target variant would share the same source set, the source set group will retain the original target's name

**Todo:**
- [x] Parsing for platform-scoped configurations
- [x] Parsing for platform-scoped references
- [x] Parsing for platform-scoped variant configurations
- [x] Parsing for platform-scoped variant references
- [x] Parsing for platform-scoped i18n-resources
- [x] Parsing for platform-scoped variant i18n-resources
- [x] Parsing for more than one platform
- [x] Preprocessing to resolve platform-scoped targets into multiple targets

### PR DESCRIPTION
**Pull request by lyptt**
Fixes #134

**Todo**

- [ ] Ensure references are resolved by the final target name (iOS, not ios)

### CODE REVIEW

**Comment by lyptt** [comment]
@yonaskolb This is now pretty much feature-complete. If you could provide feedback that would be much appreciated!

**Comment by yonaskolb** [comment]
Thanks! Going through this now, looking good! I'll list issues here as I find them. First off:

Specific platform targets are generated with the names appended with `-tvOS` and `-iOS` which is great. (They're the platforms I'm testing with) When referencing these frameworks however, the lowercase version must be used `- target: Framework-ios` instead of `- target: Axis_API-iOS`. That makes sense as that's what the platforms you defined where, but there's a mismatch with the generated target name.
Personally I think that iOS is better than ios, and the platforms should be renamed to `iOS`, `tvOS`, `watchOS`, and `macOS` to match apple's naming scheme, but that's just me

**Comment by lyptt** [comment]
Struct's identifiers are all lower-cased by convention (it's more of a Ruby convention than anything). I'll fix up the referencing so it matches the final target name, since this goes against what a user expects.

**Comment by lyptt** [comment]
@yonaskolb I'm considering changing the suffix naming anyway to underscores rather than hyphens, in Swift when you `import` the module, you have to replace the hyphen with an underscore anyway, so this may make everything a bit simpler if the target name, module name and reference name all match.

**Comment by yonaskolb** [comment]
Regarding the platform names wouldn't it be good to name them what the platforms are actually called, rather then a ruby convention? The fact that ruby is used in the background is probably just an unknown implementation detail for many people. Just my 2 cents

**Comment by lyptt** [comment]
I think this is one of those situations where we'll have to agree to disagree. I've taken your feedback on board, but for now the platform names will remain the same.

**Comment by yonaskolb** [comment]
In regards to hyphens to underscores, makes sense. I actually changed the product name of the framework so the import is without any suffix at all

**Comment by yonaskolb** [comment]
When specifying properties by platform (configuration of references), is there any way to set properties for all platforms? A $base platform or some other way?

**Comment by lyptt** [comment]
Hi @yonaskolb, yes that is supported. You can use the fully fleshed out declaration style:

```yaml
targets:
  App:
    configurations:
      $base:
        SWIFT_VERSION: 3.0
      ios: {...}
      tv: {...}
```

`$base` retains its existing behaviour of being merged into any configuration.

**Comment by yonaskolb** [comment]
Nice one!

**Comment by yonaskolb** [comment]
When I use `$base` I get an error:
```
undefined local variable or method `target' for #<StructCore::Processor::TargetCrossPlatformComponent:0x007fe78e118398>
```

```
configuration:
      $base:
        INFOPLIST_FILE: SDK/Support/Info.plist
        PRODUCT_NAME: SDK
      ios:
        FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/Carthage/Build/iOS
      tv:
        FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/Carthage/Build/tvOS
```

If I comment out the `$base` section, it generates without errors

**Comment by lyptt** [comment]
Hi @yonaskolb, it's configurations, not configuration.

**Comment by yonaskolb** [comment]
Oh whoops, thanks! I guess that might be an easy mistake for a user to make. They have a `configuration` section, and then add another platform or add a config specific setting, and they forget to rename `configuration` to `configurations`

**Comment by yonaskolb** [comment]
Renaming to `configurations` gets me a new error.
```
undefined method `map' for nil:NilClass
```
```
configurations:
      $base:
        INFOPLIST_FILE: SDK/Support/Info.plist
        PRODUCT_NAME: SDK
      ios:
        FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/Carthage/Build/iOS
      tv:
        FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/Carthage/Build/tvOS
```
Also in the example file in this PR it's using `configuration`  when specifying platforms. Is it supposed to change only when using `$base`?
 https://github.com/workshop/struct/blob/9fd01a2257fe70a732b8ed1a24b36de285312d42/examples/Cross_Platform_Application/project.yml

**Comment by lyptt** [comment]
Hi @yonaskolb, can you paste you full project file please? The error could be elsewhere in the spec file.

No, that's not the case. Both `configuration` and `configurations` support specifying platforms, as well as sources, resources and references.

**Comment by yonaskolb** [comment]
I guess the question is, in it's current state, when would you pick configuration over configurations? Plural only when specifying multiple configs? As in my example I'm not doing specifying config specific settings, only platform specific.
 
Also can can you specify both platform and configuration specific build settings and if so, in what order?

**Comment by yonaskolb** [comment]
Ok, found the minimum spec that throws the error. It seems to be when you have configurations that aren't `debug` and `release`, and also specify a multi-platform target with platform specific and $base settings:
```
version: 2.2.0
configurations:
  debug new:
    type: debug
  release:
    type: release
targets:
  MyFramework:
    sources: source
    platform:
      - ios
      - tv
    type: ":framework"
    configurations:
      $base:
        SWIFT_VERSION: '3.0'
      ios:
        INFOPLIST_FILE: Info-ios.plist
      tv:
        INFOPLIST_FILE: Info-tv.plist
```

This shows the warning and error:
```
Warning: Config name INFOPLIST_FILE for target MyFramework was not defined in this spec. Ignoring target...
undefined method `map' for nil:NilClas
```

**Comment by lyptt** [comment]
Ah yes, I see the issue now. Thanks for providing this!

You need to specify your configurations within the platform blocks, like this:

```yaml
version: 2.2.0
configurations:
  debug new:
    type: debug
  release:
    type: release
targets:
  MyFramework:
    sources: source
    platform:
      - ios
      - tv
    type: ":framework"
    configurations:
      $base:
        SWIFT_VERSION: '3.0'
      ios:
        debug new: # <----------
          INFOPLIST_FILE: Info-ios.plist
        release: # <----------
          INFOPLIST_FILE: Info-ios.plist
      tv:
        debug new: # <----------
          INFOPLIST_FILE: Info-tv.plist
        release: # <----------
          INFOPLIST_FILE: Info-tv.plist
```

A platform block does not operate the same way as $base, it's almost like a namespace for configurations. The Specfile DSL may help you understand this better, as it's a little more descriptive:

```ruby
target 'MyFramework' do
  platform 'ios' do
    configuration 'ios' do
      override 'INFOPLIST_FILE', 'Info-ios.plist'
    end
  end
end
```

**Comment by lyptt** [comment]
I think the source of your other error is most likely down to not enough validation being applied to cross-platform targets. I'll see if I can tighten that up before this is merged!

**Comment by yonaskolb** [comment]
Ok cool. So the only way to not have to repeat build settings for multiple platforms and configurations would be to use yaml anchors?

**Comment by lyptt** [comment]
Yes that's correct. Either that or using `configuration`, but if you use that you can't use `$base`. In your scenario you could use `configuration` and YAML anchors to achieve this.

**Comment by yonaskolb** [comment]
I was testing out referencing the multi-platform targets again without the upcoming fix to final target names. It seems at the moment there doesn't seem to be a workaround. Neither of these seem to work properly:
```
references:
  - target: MyFramework-ios
```
```
references:
  - target: MyFramework-iOS
```
The first one doesn't create any reference, and the second creates a broken reference and broken framework in the frameworks group with the name `MyFramework-iOS.` (note the dot suffix).

**Comment by yonaskolb** [comment]
I was trying to put together an example that showed this broken referencing behaviour but encountered a different issue?
```
version: 2.2.0
configurations:
  debug:
    type: debug
  release:
    type: release
targets:
  MyApp:
    sources:
      - AppSource
    platform: ios
    type: ":application"
    references:
      - target: MyFramework-ios
      # - target: MyFramework-ios
        copy: true
        codeSignOnCopy: true
  MyFramework:
    sources:
      - FrameworkSource
    platform:
      - ios
      - tv
    type: ":framework"
```

This shows a warning and then error:
```
Warning: SDKROOT not recognised in configuration for target: 'MyFramework'. Ignoring...
Unknown platform for target
```
Is there something incorrect I can't see in the spec?

**Comment by lyptt** [comment]
I'm thinking this'll need a little more time in the oven 😀

I'm considering copying the change for adding a source set to two targets into a seperate PR since it's a tiny change, and moving this PR to 2.3.0. That way you should still be able to achieve what you're after, in a slightly more verbose manner. Then later once this PR is merged you could migrate to what is essentially a shorthand.

**Comment by yonaskolb** [comment]
#144 might have been contributing to an issue I had here

**Comment by lyptt** [comment]
Yeah that's definitely a possibility. Xcodeproj' target generation was behaving very strangely which meant I had to rewrite one of the processor components. 

I'll merge develop into this branch and see if the new issues you've mentioned are reproducible.

**Comment by yonaskolb** [comment]
Cool, I'll test it again once 2.2.1 is merged into this 👍

**Pull request closed without merging**
